FROM node:18

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar sólo los archivos necesarios para instalar dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto de los archivos
COPY . .

# Exponer el puerto de Vite
EXPOSE 5173

# Iniciar el servidor de desarrollo
CMD ["npm", "run", "dev"]