#version: '3.8'

services:
# Contexto de la aplicación
  app:
    build: .
    environment:
      - MONGO_URI=${MONGO_URI} # Indica nombre del servicio mongo, puerto y nombre de la base de datos
      - SECRET_KEY=${SECRET_KEY}  # Clave secreta para JWT
      - SESSION_TIMEOUT=${SESSION_TIMEOUT}  # Tiempo de sesión en minutos
    ports:
      - "8000:8000" # Puertas de acceso al contenedor
    depends_on:
      - mongo

# Contexto de la base de datos
  mongo:
    image: mongo:4.4
    container_name: mongo # Nombre del contenedor
    ports:
      - "27017:27017" # Puertas de acceso al contenedor
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  mongo_data: