services:
  rk-chatbot:
    build: .
    image: rk-chatbot-image
    container_name: rk-chatbot
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - SPATIALITE_LIBRARY_PATH=${SPATIALITE_LIBRARY_PATH}
    env_file:
      - .env  # 🔹 Cargar variables de entorno desde .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-level debug --reload